languageCode = "en-us"
title = "Daniel Karlsson"
theme = "daniel"
baseURL = "https://www.danielk.se/"

[blackfriday]
angledQuotes = false

[markup]
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 1

[author]
    name = "Daniel Karlsson"
    email = "mail@danielk.se"

[[menu.main]]
    name = "home"
    weight = 10
    url = "/"
[[menu.main]]
    identifier = "garden"
    name = "Garden"
    weight = 15
    url = "/garden/"
[[menu.main]]
    name = "Professional"
    weight = 20
    url = "/categories/professional/"
[[menu.main]]
    name = "Personal"
    weight = 20
    url = "/categories/personal/"
[[menu.main]]
    name = "contact"
    weight = 30
    url = "/contact/"


[[menu.teologi]]
    name = "teologi"
    weight = 10
    url = "/garden/teologi"

