languageCode = "en-us"
title = "Daniel Karlsson"
theme = "daniel"
baseURL = "https://www.danielk.se/"

[markup]
    [markup.goldmark.renderer]
        unsafe= true
    [markup.tableOfContents]
        startLevel = 1
    [markup.goldmark.extensions]
      footnote = true

[author]
    name = "Daniel Karlsson"
    email = "mail@danielk.se"

[[menu.main]]
    name = "blog"
    weight = 10
    url = "/"
[[menu.main]]
    name = "About me"
    weight = 20
    url = "/cv/"
[[menu.main]]
    name = "Contact/Hire me"
    weight = 30
    url = "/contact/"


[[menu.teologi]]
    name = "teologi"
    weight = 10
    url = "/garden/teologi"

